"""In-process Bible verse text lookup, backed by a static bundled JSON asset.

Round 3 of task 20260904-friend-activity-push-triggers: `_friend_went_active_
notify` (scheduler.py) and `FriendsManager.get_friend_activity` (friends.py)
both need to resolve `book/chapter/verse -> plain text` at read/send time so a
highlight push/preview can show real verse content instead of a bare
reference. `bible.json` (copied here from
`FellowScript/FellowScript/Bible/bible.json`, the same asset the iOS reader
already ships) is a static, already-generated, rarely-changing ~4.2MB
reference dataset -- a DB table or an outbound third-party API call would be
real added maintenance/failure-mode surface for content that never changes at
runtime, so this is a plain in-process load instead (see
architecture-design-thinking: boring solution, least complexity for the
actual need). No DB table, no migration, no network call.

Task 20260927-esv-bible-source-migration: `bible.json` is now generated by
`backend/bibleHandling/generate_bible_data.py` from a vendored, pinned World
English Bible (WEB) source (`data/vendor/eng-web.usfx.xml`, see
`data/vendor/SOURCE.md`), not scraped from a PDF and not fetched from
api.esv.org -- both `backend/bibleHandling/archive/convertDict.py` and
`backend/bibleHandling/archive/esv_client.py` are retired, kept for history
only, and neither they nor their dependencies (fitz/pandas/spacy; the old
api.esv.org `ESV_API_KEY` credential) ever touch this module or must become
a runtime dependency here. Only the JSON the generator already produced
travels into the API image (picked up by the root Dockerfile's existing
`COPY api/ .`). See `docs/legal/bible-translation-source.md` for this
source's public-domain status (no license/attribution requirement, unlike
the retired ESV path -- see `docs/legal/archive/esv-license-status.md` for
that history).

Data shape: `bible.json` is `{book_name: [chapter_0_blob, chapter_1_blob,
...]}`, one list entry per chapter PLUS a leading index-0 empty placeholder
(so `chapters[chapter_num]` is chapter `chapter_num`'s own blob -- there is
no chapter 0). Every book, including single-chapter ones, now carries this
same uniform placeholder (a fix in its own right -- the old scraped data
omitted it inconsistently; see generate_bible_data.py's module docstring for
the full audit). Each chapter blob is a flowing-text blob of the shape
`"{chapter}:1 {verse 1 text}2{verse 2 text}3{verse 3 text}..."` -- the first
verse is prefixed `chapter:1`, every later verse is a bare verse number
immediately followed (no space) by its text's capitalized first letter, an
opening curly double quote, an opening curly single quote, or an opening
parenthesis. If present, a section subheading before verse 2+ would be
embedded inline as `HEAD::<subheading text>` (not verse content) -- in
practice the current WEB source carries no such mid-chapter headings at all
(see `web_source.py`'s docstring), so this module's `_HEAD_RE` stripping is
currently a no-op on real data, kept for forward compatibility with any
future source that does carry them. A chapter-opening heading/superscription
(before verse 1) is dropped at generation time rather than embedded, because
`_HEAD_RE` below has no digit marker to stop at before verse 1's own
un-prefixed text and would otherwise swallow it -- see `web_source.py`'s and
`generate_bible_data.py`'s module docstrings for how this was originally
found (building the now-retired ESV pipeline) and how the current WEB
pipeline avoids it by construction.

Error-handling reconciliation (Architecture/Implementation Q26/Q27,
Security Posture profile): now that the source is a controlled, machine-
generated export rather than an imperfect PDF scrape, a chapter blob that
fails to match the expected `chapter:1 ...` pattern *at all* is a genuine
data-integrity bug, not tolerable noise -- `_parse_chapter` failing to match
is now something `validate_bible_data()` (called eagerly from `main.py`'s
lifespan, same pattern as `push.py`'s `validate_apns_config`/
`gif_search.py`'s `validate_gif_config`) scans for and raises
`BibleDataError` on *before* the app starts serving traffic, so a corrupt
regeneration fails the deploy loudly instead of degrading silently.
`verse_text()` itself deliberately still returns None (never raises) on any
per-request miss, including a malformed chapter -- eager startup validation
is where "this should never happen against trustworthy data" gets enforced;
raising it back out of a single friend-activity request would take down the
whole endpoint for every user over one bad verse, a worse regression than
the status quo. A genuine per-verse miss (unrecognized book name, out-of-
range chapter/verse, or a verse number simply absent from an otherwise-
valid parsed chapter -- e.g. an enjambed Psalms verse that merges into its
neighbor) still returns None and is still the expected, handled case
callers fall back to reference-only text for (e.g. "highlighted John 3:16"
with no quoted content), matching this task's existing safe-fallback-on-one-
row posture (the same class of edge case `_friend_went_active_notify`
already documents for a missing `last_activity_type`).
"""

import json
import logging
import os
import re
import threading

logger = logging.getLogger(__name__)


class BibleDataError(RuntimeError):
    """`bible.json` itself is corrupt/malformed -- a chapter that should be
    parseable (in range per the dataset's own book/chapter counts) doesn't
    match the expected `chapter:1 ...` pattern at all. Raised by
    `validate_bible_data()` at startup (see `main.py`'s lifespan), not by
    `verse_text()` itself -- see this module's docstring for why the
    request-time path stays a quiet `None` on a miss."""

_BIBLE_JSON_PATH = os.path.join(os.path.dirname(__file__), "bible_data", "bible.json")

# Inline section subheadings ("HEAD::<text>") embedded in the flowing chapter
# text -- strip them (and their text, up to the next verse marker or the end
# of the blob) before splitting into verses; they are never verse content.
_HEAD_RE = re.compile(r"HEAD::.*?(?=\d+[A-Z“‘(]|\Z)", re.S)
# A chapter blob always opens "{chapter}:1 {verse 1 text}...".
_CHAPTER_START_RE = re.compile(r"^(\d+):1\s*(.*)", re.S)
# Every verse after the first is a bare number (not itself preceded by
# another digit -- the (?<!\d) guard keeps a multi-digit verse number from
# matching on its own trailing digits) immediately followed by a capital
# letter, an opening curly double quote, an opening curly single quote (a
# quote nested inside quoted speech), or an opening parenthesis (footnote
# markers like "[12]" are always followed by "]", never directly by one of
# these, so they never match). Kept in sync with the equivalent client-side
# verse-boundary regexes (iOS BibleReaderView.swift, frontend/src/utils.js,
# frontend/js/bible.js) as of task 20260908-bible-verse-boundary-parsing --
# this module's own character class previously lacked the curly single quote
# and opening-parenthesis cases, and the (?<!\d) guard, that the client
# copies already had.
_VERSE_SPLIT_RE = re.compile(r"(?<!\d)(\d+)(?=[A-Z“‘(])")

_raw_books: dict[str, list[str]] | None = None
_chapter_cache: dict[tuple[str, int], dict[int, str]] = {}
_load_lock = threading.Lock()


def _load_raw() -> dict[str, list[str]]:
    """Parse `bible.json` into memory on first use. A load failure (missing
    file, bad JSON) logs and leaves the lookup permanently empty for this
    process rather than raising -- every caller of `verse_text` already
    treats a miss as a normal, handled case."""
    global _raw_books
    if _raw_books is None:
        with _load_lock:
            if _raw_books is None:  # re-check inside the lock
                try:
                    with open(_BIBLE_JSON_PATH, "r", encoding="utf-8") as f:
                        _raw_books = json.load(f)
                except Exception as e:
                    logger.error("Failed to load bible.json: %s", e)
                    _raw_books = {}
    return _raw_books


def _parse_chapter(blob: str) -> dict[int, str] | None:
    """Split one chapter's raw blob into ``{verse_num: text}``, or None if it
    doesn't match the expected leading ``chapter:1 `` pattern at all."""
    cleaned = _HEAD_RE.sub("", blob)
    m = _CHAPTER_START_RE.match(cleaned)
    if not m:
        return None
    parts = _VERSE_SPLIT_RE.split(m.group(2))
    verses = {1: parts[0].strip()}
    i = 1
    while i < len(parts) - 1:
        try:
            vnum = int(parts[i])
        except ValueError:
            i += 2
            continue
        verses[vnum] = parts[i + 1].strip()
        i += 2
    return verses


def verse_text(book: str, chapter: int, verse: int) -> str | None:
    """Look up one verse's plain text. Returns None on any miss (unknown
    book, out-of-range chapter/verse, or an unparseable chapter blob) --
    never raises. See this module's docstring for the fallback contract
    callers are expected to follow on a miss."""
    if not book or not isinstance(chapter, int) or not isinstance(verse, int):
        return None
    books = _load_raw()
    chapters = books.get(book)
    if not chapters or chapter < 1 or chapter >= len(chapters):
        return None
    cache_key = (book, chapter)
    verses = _chapter_cache.get(cache_key)
    if verses is None:
        try:
            parsed = _parse_chapter(chapters[chapter])
            if parsed is None:
                # In-range chapter that doesn't match the expected pattern
                # at all -- against a trustworthy, generated source this
                # shouldn't happen; log it as a data-integrity signal (not
                # just a routine miss) so it's discoverable, but still
                # return None here rather than raising -- see this module's
                # docstring for why request-time stays quiet and
                # validate_bible_data() is where this gets enforced loudly.
                logger.error(
                    "DATA INTEGRITY: %s chapter %d is in range but its blob doesn't "
                    "match the expected 'chapter:1 ...' pattern -- bible.json may be "
                    "corrupt or was regenerated incorrectly. See validate_bible_data().",
                    book, chapter,
                )
            verses = parsed or {}
        except Exception as e:
            logger.error("Failed to parse %s %d: %s", book, chapter, e)
            verses = {}
        _chapter_cache[cache_key] = verses
    return verses.get(verse)


def validate_bible_data() -> None:
    """Eagerly load `bible.json` and confirm every chapter of every book
    parses -- called from `main.py`'s lifespan, same pattern as
    `push.py`'s `validate_apns_config`/`gif_search.py`'s
    `validate_gif_config`/etc. A missing file, unreadable JSON, a book
    missing entirely, or any in-range chapter that fails to parse is a
    `BibleDataError` raised here (and *only* here -- `verse_text()` itself
    stays request-safe and never raises; see this module's docstring).
    Deliberately not caught by the caller -- a corrupt Bible dataset should
    fail the deploy loudly, not silently degrade every highlight
    preview/push indefinitely.
    """
    books = _load_raw()
    if not books:
        raise BibleDataError(f"bible.json failed to load from {_BIBLE_JSON_PATH} (see prior log line).")

    bad: list[str] = []
    for book, chapters in books.items():
        if not isinstance(chapters, list) or len(chapters) < 2:
            bad.append(f"{book}: expected a list with a placeholder + at least one chapter, got {chapters!r}")
            continue
        for chapter_num in range(1, len(chapters)):
            if _parse_chapter(chapters[chapter_num]) is None:
                bad.append(f"{book} {chapter_num}: does not match the expected 'chapter:1 ...' pattern")

    if bad:
        raise BibleDataError(
            f"bible.json failed validation ({len(bad)} issue(s)):\n" + "\n".join(bad[:50])
            + ("\n... (truncated)" if len(bad) > 50 else "")
        )


MAX_VERSE_NUMBER = 176  # Psalm 119, the longest chapter in the Bible.


def is_valid_reference(book: str, chapter: int, verse: int) -> bool:
    """True if (book, chapter, verse) is a plausible Bible reference: `book`
    is one of this dataset's exact 66 known keys, `chapter` is in range for
    that book, and `verse` is a positive integer within `MAX_VERSE_NUMBER`.

    This deliberately does NOT require `verse_text(...)` to resolve non-None
    for that reference -- this module's own docstring documents legitimate
    parse gaps (e.g. some enjambed Psalms verses) where a real, in-range
    verse still can't be isolated from its chapter blob; rejecting those as
    "invalid" would be a functional regression, not a security fix.

    Added for task 20260904-friend-activity-push-triggers: prior to that
    task, `book`/`chapter`/`verse` on a highlight were accepted at
    `POST /notes/highlight/{user_id}` with no format/range check beyond
    truthiness, which was harmless while a highlight's reference was never
    shown to anyone (see friends.py's now-superseded docstring on that
    point). Now that a highlight's reference is exposed to friends --
    directly in a push notification body and in the friend-activity widget,
    verbatim, whenever `verse_text` can't resolve real content -- an
    unvalidated `book` string is a stored content-injection vector into a
    second user's device notification, not just this user's own data
    anymore. Reject at write time instead.
    """
    if not isinstance(book, str) or not isinstance(chapter, int) or not isinstance(verse, int):
        return False
    if isinstance(chapter, bool) or isinstance(verse, bool):  # bool is an int subclass
        return False
    chapters = _load_raw().get(book)
    if not chapters or chapter < 1 or chapter >= len(chapters):
        return False
    return 1 <= verse <= MAX_VERSE_NUMBER


def parse_highlight_key(key: str) -> tuple[str, int, int] | None:
    """Split a ``highlights.key`` value (``f"{book}-{chapter}-{verse}"``, see
    ``routes/notes.py``'s ``highlight_verse``) back into ``(book, chapter,
    verse)``. None of this app's fixed 66 Bible book names contain a dash, so
    the last two dash-separated segments are always chapter/verse -- but
    this is read defensively against any historical/malformed key rather
    than assumed: a missing/non-numeric chapter or verse component returns
    None instead of raising."""
    if not key:
        return None
    parts = key.rsplit("-", 2)
    if len(parts) != 3:
        return None
    book, chapter_s, verse_s = parts
    try:
        return book, int(chapter_s), int(verse_s)
    except ValueError:
        return None
